name: user_list_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Json serialization
  json_annotation: ^4.0.1

  # Bloc design pattern
  flutter_bloc: ^9.0.0
  hooked_bloc: ^1.6.0


  # Great library for utilities , observation , navigation and dependencies
  get: ^4.1.1

  # Dependency injection
  # get_it: ^6.0.0
  get_it: ^8.0.3
  # injectable: ^1.2.2
  injectable: ^2.5.0

  # Networking library
  # retrofit: ^2.0.0-beta1
  retrofit: ^4.4.2
  dio: ^5.7.0
  # pretty_dio_logger: ^1.1.1
  flutter_pretty_dio_logger: ^3.0.0
  # logger: ^1.0.0
  logger: ^2.5.0

  # Shared preferences
  shared_preferences: ^2.0.3 #for storing user credentials persistence

  # Connectivity
  connectivity_plus: ^6.1.3

  # VelocityX for UI Chain features as swift UI
  velocity_x: ^4.3.0

  # Web responsive
  sizer: ^3.0.5

  #Freezed for unions/pattern-matching/copy.
  freezed: ^2.0.4

  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Build run for commands
  build_runner:

  # Json serialization
  json_serializable: ^6.3.0

  #Networking generator
  retrofit_generator: ^9.1.9

  # Dependency injection generator
  injectable_generator: ^2.7.0

  bloc_test: ^9.1.0
  mockito: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/image_loader.html
    - assets/double_ring_loading_io.gif

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
