name: common_library
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Json serialization
  json_annotation: ^4.0.1

  # Bloc design pattern
  flutter_bloc: ^7.3.1
  # flutter_bloc: ^8.0.1
  # flutter_hooks_bloc: ^0.15.0+1
  flutter_hooks_bloc: ^0.16.0

  # Great library for utilities , observation , navigation and dependencies
  get: ^4.1.1

  # Dependency injection
  # get_it: ^6.0.0
  get_it: ^7.2.0
  # injectable: ^1.2.2
  injectable: ^1.5.3

  # Networking library
  # retrofit: ^2.0.0-beta1
  retrofit: ^3.0.1+1
  # pretty_dio_logger: ^1.1.1
  flutter_pretty_dio_logger: ^2.0.0
  # logger: ^1.0.0
  logger: ^1.1.0


  # Connectivity
  connectivity: ^3.0.3

  # VelocityX for UI Chain features as swift UI
  velocity_x: ^3.3.0

  # Web responsive
  sizer: ^2.0.11

  #Freezed for unions/pattern-matching/copy.
  # freezed: ^0.14.1+1
  freezed: ^2.0.4
  

  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Build run for commands
  build_runner:

  # Json serialization
  # json_serializable: ^4.1.0
  json_serializable: ^6.3.0

  # Dependency injection generator
  # injectable_generator: ^1.2.2
  injectable_generator: ^1.5.3

  #Networking generator
  # retrofit_generator: ^2.0.0-beta3
  retrofit_generator: ^4.0.1

  #Freezed for unions/pattern-matching/copy.
  # freezed: ^0.14.1+1
  freezed: ^2.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/image_loader.html
    - assets/double_ring_loading_io.gif
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
